name: Check LaTeX syntax
on:
  push:
    branches:
      - main
      - Optimizacija-CI
jobs:

  compile_pdf:
  
    name: Compile document
    
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMPILING_TOKEN }}
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          
      - name: pdflatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            1. letnik/Algebra 1/Algebra 1.tex
            1. letnik/Analiza 1/Analiza 1.tex
            1. letnik/Logika in množice/Logika in množice.tex
            2. letnik/Algebra 2/Algebra 2.tex
            2. letnik/Analiza 2a/Analiza 2.tex
            2. letnik/Splošna topologija/Splošna topologija.tex
          compiler: pdflatex
          args: -interaction=nonstopmode
