name: Check LaTeX syntax
on:
  push:
    branches:
      - main

jobs:

  compile_pdf:
  
    name: Compile document
    
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMPILING_TOKEN }}
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          
      - name: pdflatex
        uses: xu-cheng/latex-action@v2.5.0
        with:
          root_file: |
            *letnik/*/*.tex
          work_in_root_file_dir: true
          glob_root_file: true
          compiler: pdflatex
          args: -interaction=nonstopmode
