name: Build LaTeX document
on: pull_request_target
jobs:

  check_file_changes:
    name: Preveri spremembe datotek
    runs-on: ubuntu-latest
    outputs:
      updated_tex_file: ${{ steps.changes.outputs.tex_file }}
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMPILING_TOKEN }}
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          
      - name: Create filter
        uses: dorny/paths-filter@v2
        id: changes
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          filters: |
            tex_file:
              - '**.tex'
    
  compile_pdf:
    name: Compile document
    needs: check_file_changes
    if: ${{ needs.check_file_changes.outputs.updated_tex_file == 'true' }}
    
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMPILING_TOKEN }}
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
              
      - name: Prvi pdflatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            *letnik/*/*.tex
          work_in_root_file_dir: true
          glob_root_file: true
          compiler: pdflatex
          args: -interaction=nonstopmode
          
      - name: Bibliografija
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            *letnik/*/*.bcf
          work_in_root_file_dir: true
          glob_root_file: true
          compiler: biber
          args: ''

      - name: Stvarno kazalo
        run: |
          sudo apt install xindy
          for letnik in *letnik/ ; do
            cd "$letnik"
            for predmet in */ ; do
              if [[ ${predmet:0:1} == "." ]]; then
                continue
              fi
              cd "$predmet"
              texindy -L slovenian -C utf8 *.idx
              cd ..
            done
            cd ..
          done
          
      - name: Drugi pdflatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            *letnik/*/*.tex
          work_in_root_file_dir: true
          glob_root_file: true
          compiler: pdflatex
          args: -interaction=nonstopmode
          
      - name: Tretji pdflatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            *letnik/*/*.tex
          work_in_root_file_dir: true
          glob_root_file: true
          compiler: pdflatex
          args: -interaction=nonstopmode
            
      - name: Create filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            pdf:
              -  "*letnik/*/*.pdf"
            tex:
              -  "*letnik/*/*.tex"
          list-files: shell
          
      - name: Add pdfs
        run: |
          for letnik in *letnik/ ; do
            cd "$letnik"
            for predmet in */ ; do
              if [[ ${predmet:0:1} == "." ]]; then
                continue
              fi
              cd "$predmet"
              if [[ ${{ steps.filter.outputs.tex }} =~ (^|[[:space:]])"$predmet".tex($|[[:space:]]) ]] ; then
                if [[ !${{ steps.filter.outputs.pdf }} =~ (^|[[:space:]])"$predmet".pdf($|[[:space:]]) ]] ; then
                  git add "$predmet".pdf
                  git commit -m "Dodan pdf - $predmet"
                fi
              fi
              cd ..
            done
            cd ..
          done

      - name: Push pdf files
        run: |
            git config --global user.name "Luka Horjak"
            git config --global user.email "luka1.horjak@gmail.com"
            git push origin ${{ github.event.pull_request.head.ref }}
  
  finish_job:
    name: Finish
    runs-on: ubuntu-latest
    needs: compile_pdf
    if: always()
    steps:
    
      - name: Fail if compilation failed
        if: ${{ needs.compile_pdf.result == 'failure' }}
        run: exit 1
            
      - name: Finish
        run: echo "Action complete"
